
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navi.captchaapi.parser_lexer.db;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DB_CAPTCHAS = 2;
  public static final int RBRACE = 13;
  public static final int RPAREN = 11;
  public static final int DIGIT = 17;
  public static final int USADO = 6;
  public static final int ULTIMO_USO = 9;
  public static final int LPAREN = 10;
  public static final int COLON = 15;
  public static final int LBRACE = 12;
  public static final int ID = 3;
  public static final int STRING = 14;
  public static final int COMMA = 16;
  public static final int FALLOS = 8;
  public static final int NOMBRE = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int HTML = 5;
  public static final int ACIERTOS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DB_CAPTCHAS",
  "ID",
  "NOMBRE",
  "HTML",
  "USADO",
  "ACIERTOS",
  "FALLOS",
  "ULTIMO_USO",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "STRING",
  "COLON",
  "COMMA",
  "DIGIT"
  };
}

